services:
  step-ca:
    image: 'smallstep/step-ca:latest'
    environment:
      - 'SERVICE_FQDN_STEPCA_9000=ca.myperformance.pl'
      - 'DOCKER_STEPCA_INIT_NAME=MyPerformance Internal CA'
      - 'DOCKER_STEPCA_INIT_DNS_NAMES=ca.myperformance.pl,localhost,step-ca'
      - 'DOCKER_STEPCA_INIT_PROVISIONER_NAME=admin@myperformance.pl'
      - 'DOCKER_STEPCA_INIT_PASSWORD=${SERVICE_PASSWORD_64_CAPASSWORD}'
      - 'DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true'
      - 'DOCKER_STEPCA_INIT_ACME=false'
      - 'DOCKER_STEPCA_INIT_SSH=false'
      - 'DOCKER_STEPCA_INIT_ADDRESS=:9000'
    volumes:
      - 'stepca-data:/home/step'
    healthcheck:
      test:
        - CMD-SHELL
        - 'step ca health >/dev/null 2>&1 || exit 1'
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s
