/**
 * Katalog kafelków/sub-views — single source of truth dla:
 *   - dashboard tile rendering (filtrowane po area)
 *   - Cmd+K palette search (matching po keywords + tagach z Directus)
 *   - mp_app_catalog Directus collection seed
 *
 * Tagi są dynamiczne — admin edytuje w Directusie, dashboard pull-uje
 * przy każdym search request (z 60s in-memory cache).
 */

export interface AppCatalogEntry {
  id: string;
  title: string;
  subtitle: string;
  href: string;
  /** Hardcoded keywords (PL ASCII fold-friendly) — match po IN-CODE. */
  keywords: string;
  /** Area required do zobaczenia. null = każdy zalogowany. */
  requiresArea: string | null;
  requiresMinPriority?: number;
  /** Default tagi suggesting w Directusie (przykłady dla admina). */
  defaultTags?: string[];
}

export const APP_CATALOG: AppCatalogEntry[] = [
  // Główne panele admin
  {
    id: "/admin/infrastructure",
    title: "Infrastruktura serwera",
    subtitle: "VPS, DNS, Zasoby, Bezpieczeństwo, Wazuh",
    href: "/admin/infrastructure",
    keywords: "vps dns snapshot resources cpu ram security wazuh siem",
    requiresArea: "infrastructure",
    requiresMinPriority: 90,
    defaultTags: ["serwer", "monitoring", "wazuh", "snapshot", "backup"],
  },
  {
    id: "/admin/email",
    title: "Email — centralne zarządzanie",
    subtitle: "Branding, KC templates, Postal, OVH",
    href: "/admin/email",
    keywords: "email branding template postal ovh smtp mail",
    requiresArea: "email-admin",
    requiresMinPriority: 90,
    defaultTags: ["email", "smtp", "szablon", "branding", "newsletter"],
  },
  {
    id: "/admin/users",
    title: "Użytkownicy",
    subtitle: "Lista, role, uprawnienia",
    href: "/admin/users",
    keywords: "users uzytkownicy konta role uprawnienia permissions kc keycloak",
    requiresArea: "keycloak",
    requiresMinPriority: 90,
    defaultTags: ["uzytkownicy", "iam", "role", "permissions", "keycloak"],
  },
  {
    id: "/admin/users?tab=groups",
    title: "Grupy",
    subtitle: "Persony — zestawy ról",
    href: "/admin/users?tab=groups",
    keywords: "grupy groups personas roles",
    requiresArea: "keycloak",
    requiresMinPriority: 90,
    defaultTags: ["grupy", "persony", "iam", "role"],
  },
  {
    id: "/admin/certificates",
    title: "Certyfikaty klienckie",
    subtitle: "step-ca, mTLS, PKCS12",
    href: "/admin/certificates",
    keywords: "certyfikaty mtls step-ca pki client cert pkcs12",
    requiresArea: "certificates",
    requiresMinPriority: 90,
    defaultTags: ["certyfikat", "mtls", "pki", "podpis", "tls"],
  },
  {
    id: "/admin/locations",
    title: "Punkty (sklepy / serwisy)",
    subtitle: "Mapa, kontakt, godziny, plan budżetu",
    href: "/admin/locations",
    keywords: "punkty sklepy serwis mapa lokalizacja adres godziny",
    requiresArea: "certificates",
    requiresMinPriority: 90,
    defaultTags: ["punkty", "mapa", "sklep", "serwis", "lokalizacja"],
  },
  {
    id: "/admin/config",
    title: "Zarządzanie konfiguracją",
    subtitle: "Hub: punkty + certyfikaty + powiązania w jednym miejscu",
    href: "/admin/config",
    keywords:
      "konfiguracja punkty certyfikaty powiązania hub centralne zarządzanie",
    requiresArea: "certificates",
    requiresMinPriority: 90,
    defaultTags: ["konfiguracja", "hub", "powiązania", "certyfikaty", "punkty"],
  },
  // Sub-views w infrastructure
  {
    id: "/admin/infrastructure?tab=vps",
    title: "VPS + Backup",
    subtitle: "Snapshoty, OVH, restore",
    href: "/admin/infrastructure?tab=vps",
    keywords: "vps backup snapshot ovh restore image",
    requiresArea: "infrastructure",
    requiresMinPriority: 90,
    defaultTags: ["vps", "backup", "snapshot", "restore"],
  },
  {
    id: "/admin/infrastructure?tab=dns",
    title: "DNS Zone",
    subtitle: "Domeny, rekordy DNS",
    href: "/admin/infrastructure?tab=dns",
    keywords: "dns domain rekord zone",
    requiresArea: "infrastructure",
    requiresMinPriority: 90,
    defaultTags: ["dns", "domena", "rekord"],
  },
  {
    id: "/admin/infrastructure?tab=resources",
    title: "Zasoby (CPU/RAM/Disk)",
    subtitle: "Metryki + Docker stats",
    href: "/admin/infrastructure?tab=resources",
    keywords: "cpu ram disk docker zasoby metryki resources",
    requiresArea: "infrastructure",
    requiresMinPriority: 90,
    defaultTags: ["zasoby", "monitoring", "cpu", "ram", "disk"],
  },
  {
    id: "/admin/infrastructure?tab=security",
    title: "Bezpieczeństwo / Alerty",
    subtitle: "Security events, severity, alert log",
    href: "/admin/infrastructure?tab=security",
    keywords: "alerty security events severity bezpieczenstwo",
    requiresArea: "infrastructure",
    requiresMinPriority: 90,
    defaultTags: ["bezpieczenstwo", "alert", "incident"],
  },
  {
    id: "/admin/infrastructure?tab=blocks",
    title: "Threat Intel — IP",
    subtitle: "Blokady, risk score, geolokacja",
    href: "/admin/infrastructure?tab=blocks",
    keywords: "ip block threat blocked iptables wazuh risk score blocks",
    requiresArea: "infrastructure",
    requiresMinPriority: 90,
    defaultTags: ["ip", "blokada", "threat", "wazuh"],
  },
  {
    id: "/admin/infrastructure?tab=map",
    title: "Mapa zdarzeń",
    subtitle: "Geo + timeline + correlations",
    href: "/admin/infrastructure?tab=map",
    keywords: "map mapa events timeline correlations attack geo",
    requiresArea: "infrastructure",
    requiresMinPriority: 90,
    defaultTags: ["mapa", "geo", "atak", "timeline"],
  },
  {
    id: "/admin/infrastructure?tab=devices",
    title: "Urządzenia",
    subtitle: "Device fingerprinting, sightings",
    href: "/admin/infrastructure?tab=devices",
    keywords: "devices urzadzenia fingerprint cookie",
    requiresArea: "infrastructure",
    requiresMinPriority: 90,
    defaultTags: ["urzadzenia", "fingerprint", "device"],
  },
  {
    id: "/admin/infrastructure?tab=wazuh",
    title: "Wazuh SIEM",
    subtitle: "Agenty, reguły, AR",
    href: "/admin/infrastructure?tab=wazuh",
    keywords: "wazuh siem agent rule active response",
    requiresArea: "infrastructure",
    requiresMinPriority: 90,
    defaultTags: ["wazuh", "siem", "agent", "ids"],
  },
  // Sub-views w /admin/email
  {
    id: "/admin/email?tab=templates",
    title: "Szablony emaili",
    subtitle: "Edytor + preview + włącz/wyłącz",
    href: "/admin/email?tab=templates",
    keywords: "szablony templates email mail kc keycloak",
    requiresArea: "email-admin",
    requiresMinPriority: 90,
    defaultTags: ["szablon", "email", "newsletter"],
  },
  {
    id: "/admin/email?tab=branding",
    title: "Branding emaili",
    subtitle: "Logo, accent, footer",
    href: "/admin/email?tab=branding",
    keywords: "branding logo kolor footer mail email",
    requiresArea: "email-admin",
    requiresMinPriority: 90,
    defaultTags: ["branding", "logo", "marka"],
  },
  {
    id: "/admin/email?tab=smtp",
    title: "Konfiguracje SMTP",
    subtitle: "Aliasy, transactional/marketing",
    href: "/admin/email?tab=smtp",
    keywords: "smtp konfig email transactional marketing",
    requiresArea: "email-admin",
    requiresMinPriority: 90,
    defaultTags: ["smtp", "email", "konfig"],
  },
  {
    id: "/admin/email?tab=postal",
    title: "Postal (infrastruktura)",
    subtitle: "Organizacje, serwery, domeny",
    href: "/admin/email?tab=postal",
    keywords: "postal mail server organization domain dkim",
    requiresArea: "postal",
    requiresMinPriority: 90,
    defaultTags: ["postal", "mta", "dkim", "spf"],
  },
  // Konto (każdy user)
  {
    id: "/account",
    title: "Profil",
    subtitle: "Imię, nazwisko, email",
    href: "/account",
    keywords: "profil profile imie nazwisko email konto account",
    requiresArea: null,
    defaultTags: ["profil", "konto"],
  },
  {
    id: "/account?tab=security",
    title: "Bezpieczeństwo (2FA, hasło)",
    subtitle: "TOTP + WebAuthn + zmiana hasła",
    href: "/account?tab=security",
    keywords: "bezpieczenstwo 2fa totp webauthn haslo password security",
    requiresArea: null,
    defaultTags: ["2fa", "totp", "webauthn", "haslo", "bezpieczenstwo"],
  },
  {
    id: "/account?tab=sessions",
    title: "Aktywne sesje",
    subtitle: "Lista urządzeń + wyloguj",
    href: "/account?tab=sessions",
    keywords: "sesje sessions urzadzenia wyloguj logout",
    requiresArea: null,
    defaultTags: ["sesja", "logout", "urzadzenie"],
  },
  {
    id: "/account?tab=integrations",
    title: "Integracje",
    subtitle: "Google, Kadromierz, Akademia",
    href: "/account?tab=integrations",
    keywords: "integracje integrations google kadromierz moodle akademia",
    requiresArea: null,
    defaultTags: ["integracje", "google", "kadromierz"],
  },
  {
    id: "/account?tab=activity",
    title: "Logi aktywności",
    subtitle: "Audit-trail Twojego konta",
    href: "/account?tab=activity",
    keywords: "logi log activity aktywnosc audit",
    requiresArea: null,
    defaultTags: ["log", "audit", "aktywnosc"],
  },
  {
    id: "/account?tab=preferences",
    title: "Preferencje",
    subtitle: "Wskazówki + powiadomienia",
    href: "/account?tab=preferences",
    keywords: "preferencje preferences wskazowki hints powiadomienia notifications",
    requiresArea: null,
    defaultTags: ["preferencje", "powiadomienia"],
  },
  // Aplikacje
  {
    id: "/dashboard/calendar",
    title: "Kalendarz",
    subtitle: "Twoje wydarzenia + integracje",
    href: "/dashboard/calendar",
    keywords: "kalendarz calendar wydarzenia events google moodle",
    requiresArea: null,
    defaultTags: ["kalendarz", "events", "wydarzenia", "spotkanie"],
  },
  {
    id: "/api/documenso/sso",
    title: "Dokumenty (Documenso)",
    subtitle: "Podpisy elektroniczne",
    href: "/api/documenso/sso",
    keywords: "dokumenty documents documenso podpis signature",
    requiresArea: "documenso",
    requiresMinPriority: 10,
    defaultTags: ["umowa", "podpis", "dokument", "nda", "sign", "documenso"],
  },
  {
    id: "/api/moodle/launch",
    title: "Akademia (Moodle)",
    subtitle: "Kursy, szkolenia, oceny",
    href: "/api/moodle/launch",
    keywords: "akademia moodle kursy courses szkolenia",
    requiresArea: "moodle",
    requiresMinPriority: 10,
    defaultTags: ["kurs", "szkolenie", "moodle", "akademia", "ocena"],
  },
  {
    id: "/api/chatwoot/sso",
    title: "Chatwoot",
    subtitle: "Live-chat z klientami",
    href: "/api/chatwoot/sso",
    keywords: "chatwoot chat live customer support",
    requiresArea: "chatwoot",
    requiresMinPriority: 10,
    defaultTags: ["chat", "wsparcie", "klient", "support"],
  },
  {
    id: "/api/outline/launch",
    title: "Baza wiedzy (Outline)",
    subtitle: "Procedury, how-to",
    href: "/api/outline/launch",
    keywords: "baza wiedzy outline knowledge procedury how-to wiki",
    requiresArea: "knowledge",
    requiresMinPriority: 10,
    defaultTags: ["wiki", "wiedza", "procedura", "outline", "instrukcja"],
  },
  {
    id: "/api/directus/launch",
    title: "Directus CMS",
    subtitle: "Zarządzanie treścią",
    href: "/api/directus/launch",
    keywords: "directus cms tresc content collections",
    requiresArea: "directus",
    requiresMinPriority: 10,
    defaultTags: ["cms", "directus", "kolekcja", "tresc"],
  },
  {
    id: "https://postal.myperformance.pl",
    title: "Postal — admin",
    subtitle: "Native UI Postal",
    href: "https://postal.myperformance.pl",
    keywords: "postal admin email server native",
    requiresArea: "postal",
    requiresMinPriority: 90,
    defaultTags: ["postal", "mta"],
  },
  {
    id: "/admin/keycloak",
    title: "Keycloak admin",
    subtitle: "Realm, klienci, IdP",
    href: "/admin/keycloak",
    keywords: "keycloak idp realm clients admin console",
    requiresArea: "keycloak",
    requiresMinPriority: 90,
    defaultTags: ["keycloak", "idp", "realm", "iam"],
  },
];
